//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advarics.ControlService.TestClient.AdvaricsControlService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UploadFileRequest", Namespace="http://schemas.datacontract.org/2004/07/Advarics.ControlService.DataContracts.Fil" +
        "eTransfer")]
    [System.SerializableAttribute()]
    public partial class UploadFileRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdateOrdnerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdToken {
            get {
                return this.IdTokenField;
            }
            set {
                if ((this.IdTokenField.Equals(value) != true)) {
                    this.IdTokenField = value;
                    this.RaisePropertyChanged("IdToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdateOrdner {
            get {
                return this.UpdateOrdnerField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateOrdnerField, value) != true)) {
                    this.UpdateOrdnerField = value;
                    this.RaisePropertyChanged("UpdateOrdner");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UploadInfoResponse", Namespace="http://schemas.datacontract.org/2004/07/Advarics.ControlService.DataContracts.Fil" +
        "eTransfer")]
    [System.SerializableAttribute()]
    public partial class UploadInfoResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Advarics.ControlService.TestClient.AdvaricsControlService.LogResponse[] LogsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Advarics.ControlService.TestClient.AdvaricsControlService.LogResponse[] Logs {
            get {
                return this.LogsField;
            }
            set {
                if ((object.ReferenceEquals(this.LogsField, value) != true)) {
                    this.LogsField = value;
                    this.RaisePropertyChanged("Logs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogResponse", Namespace="http://schemas.datacontract.org/2004/07/Advarics.ControlService.DataContracts.Fil" +
        "eTransfer")]
    [System.SerializableAttribute()]
    public partial class LogResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Exception ExceptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WorkerErrorCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime WorkerStartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool WorkerSuccessfulField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long workerPackageNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Exception Exception {
            get {
                return this.ExceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionField, value) != true)) {
                    this.ExceptionField = value;
                    this.RaisePropertyChanged("Exception");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Info {
            get {
                return this.InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoField, value) != true)) {
                    this.InfoField = value;
                    this.RaisePropertyChanged("Info");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path {
            get {
                return this.PathField;
            }
            set {
                if ((object.ReferenceEquals(this.PathField, value) != true)) {
                    this.PathField = value;
                    this.RaisePropertyChanged("Path");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServerName {
            get {
                return this.ServerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ServerNameField, value) != true)) {
                    this.ServerNameField = value;
                    this.RaisePropertyChanged("ServerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WorkerErrorCount {
            get {
                return this.WorkerErrorCountField;
            }
            set {
                if ((this.WorkerErrorCountField.Equals(value) != true)) {
                    this.WorkerErrorCountField = value;
                    this.RaisePropertyChanged("WorkerErrorCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime WorkerStartTime {
            get {
                return this.WorkerStartTimeField;
            }
            set {
                if ((this.WorkerStartTimeField.Equals(value) != true)) {
                    this.WorkerStartTimeField = value;
                    this.RaisePropertyChanged("WorkerStartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool WorkerSuccessful {
            get {
                return this.WorkerSuccessfulField;
            }
            set {
                if ((this.WorkerSuccessfulField.Equals(value) != true)) {
                    this.WorkerSuccessfulField = value;
                    this.RaisePropertyChanged("WorkerSuccessful");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long workerPackageNo {
            get {
                return this.workerPackageNoField;
            }
            set {
                if ((this.workerPackageNoField.Equals(value) != true)) {
                    this.workerPackageNoField = value;
                    this.RaisePropertyChanged("workerPackageNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VersionRequest", Namespace="http://schemas.datacontract.org/2004/07/Advarics.ControlService.DataContracts.Ver" +
        "sionInfo")]
    [System.SerializableAttribute()]
    public partial class VersionRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BaseProgramPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Advarics.ControlService.TestClient.AdvaricsControlService.CustomerInfo CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdTokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BaseProgramPath {
            get {
                return this.BaseProgramPathField;
            }
            set {
                if ((object.ReferenceEquals(this.BaseProgramPathField, value) != true)) {
                    this.BaseProgramPathField = value;
                    this.RaisePropertyChanged("BaseProgramPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Advarics.ControlService.TestClient.AdvaricsControlService.CustomerInfo Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdToken {
            get {
                return this.IdTokenField;
            }
            set {
                if ((this.IdTokenField.Equals(value) != true)) {
                    this.IdTokenField = value;
                    this.RaisePropertyChanged("IdToken");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerInfo", Namespace="http://schemas.datacontract.org/2004/07/Advarics.ControlService.DataContracts.Ver" +
        "sionInfo")]
    [System.SerializableAttribute()]
    public partial class CustomerInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BaseCustomerPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DBNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long NoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BaseCustomerPath {
            get {
                return this.BaseCustomerPathField;
            }
            set {
                if ((object.ReferenceEquals(this.BaseCustomerPathField, value) != true)) {
                    this.BaseCustomerPathField = value;
                    this.RaisePropertyChanged("BaseCustomerPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DBName {
            get {
                return this.DBNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DBNameField, value) != true)) {
                    this.DBNameField = value;
                    this.RaisePropertyChanged("DBName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long No {
            get {
                return this.NoField;
            }
            set {
                if ((this.NoField.Equals(value) != true)) {
                    this.NoField = value;
                    this.RaisePropertyChanged("No");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VersionInfoResponse", Namespace="http://schemas.datacontract.org/2004/07/Advarics.ControlService.DataContracts.Ver" +
        "sionInfo")]
    [System.SerializableAttribute()]
    public partial class VersionInfoResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Advarics.ControlService.TestClient.AdvaricsControlService.CashVersion[] CashVersionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Advarics.ControlService.TestClient.AdvaricsControlService.LogResponse[] LogsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RentalServicePakNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RetailDBVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RetailPakNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RetailProgramVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SecuDataServicePakNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long StatisticServicePakNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long WebShopServicePakNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Advarics.ControlService.TestClient.AdvaricsControlService.CashVersion[] CashVersions {
            get {
                return this.CashVersionsField;
            }
            set {
                if ((object.ReferenceEquals(this.CashVersionsField, value) != true)) {
                    this.CashVersionsField = value;
                    this.RaisePropertyChanged("CashVersions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Advarics.ControlService.TestClient.AdvaricsControlService.LogResponse[] Logs {
            get {
                return this.LogsField;
            }
            set {
                if ((object.ReferenceEquals(this.LogsField, value) != true)) {
                    this.LogsField = value;
                    this.RaisePropertyChanged("Logs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RentalServicePakNo {
            get {
                return this.RentalServicePakNoField;
            }
            set {
                if ((this.RentalServicePakNoField.Equals(value) != true)) {
                    this.RentalServicePakNoField = value;
                    this.RaisePropertyChanged("RentalServicePakNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RetailDBVersion {
            get {
                return this.RetailDBVersionField;
            }
            set {
                if ((this.RetailDBVersionField.Equals(value) != true)) {
                    this.RetailDBVersionField = value;
                    this.RaisePropertyChanged("RetailDBVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RetailPakNo {
            get {
                return this.RetailPakNoField;
            }
            set {
                if ((this.RetailPakNoField.Equals(value) != true)) {
                    this.RetailPakNoField = value;
                    this.RaisePropertyChanged("RetailPakNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RetailProgramVersion {
            get {
                return this.RetailProgramVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.RetailProgramVersionField, value) != true)) {
                    this.RetailProgramVersionField = value;
                    this.RaisePropertyChanged("RetailProgramVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SecuDataServicePakNo {
            get {
                return this.SecuDataServicePakNoField;
            }
            set {
                if ((this.SecuDataServicePakNoField.Equals(value) != true)) {
                    this.SecuDataServicePakNoField = value;
                    this.RaisePropertyChanged("SecuDataServicePakNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long StatisticServicePakNo {
            get {
                return this.StatisticServicePakNoField;
            }
            set {
                if ((this.StatisticServicePakNoField.Equals(value) != true)) {
                    this.StatisticServicePakNoField = value;
                    this.RaisePropertyChanged("StatisticServicePakNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long WebShopServicePakNo {
            get {
                return this.WebShopServicePakNoField;
            }
            set {
                if ((this.WebShopServicePakNoField.Equals(value) != true)) {
                    this.WebShopServicePakNoField = value;
                    this.RaisePropertyChanged("WebShopServicePakNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CashVersion", Namespace="http://schemas.datacontract.org/2004/07/Advarics.ControlService.DataContracts.Ver" +
        "sionInfo")]
    [System.SerializableAttribute()]
    public partial class CashVersion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastSyncField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long StoreNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SyncField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long UpdatePackageCashPointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long UpdatePackageSyncServiceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastSync {
            get {
                return this.LastSyncField;
            }
            set {
                if ((this.LastSyncField.Equals(value) != true)) {
                    this.LastSyncField = value;
                    this.RaisePropertyChanged("LastSync");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long No {
            get {
                return this.NoField;
            }
            set {
                if ((this.NoField.Equals(value) != true)) {
                    this.NoField = value;
                    this.RaisePropertyChanged("No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long StoreNo {
            get {
                return this.StoreNoField;
            }
            set {
                if ((this.StoreNoField.Equals(value) != true)) {
                    this.StoreNoField = value;
                    this.RaisePropertyChanged("StoreNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Sync {
            get {
                return this.SyncField;
            }
            set {
                if ((this.SyncField.Equals(value) != true)) {
                    this.SyncField = value;
                    this.RaisePropertyChanged("Sync");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UpdatePackageCashPoint {
            get {
                return this.UpdatePackageCashPointField;
            }
            set {
                if ((this.UpdatePackageCashPointField.Equals(value) != true)) {
                    this.UpdatePackageCashPointField = value;
                    this.RaisePropertyChanged("UpdatePackageCashPoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UpdatePackageSyncService {
            get {
                return this.UpdatePackageSyncServiceField;
            }
            set {
                if ((this.UpdatePackageSyncServiceField.Equals(value) != true)) {
                    this.UpdatePackageSyncServiceField = value;
                    this.RaisePropertyChanged("UpdatePackageSyncService");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateRequest", Namespace="http://schemas.datacontract.org/2004/07/Advarics.ControlService.DataContracts.Upd" +
        "ateInfo")]
    [System.SerializableAttribute()]
    public partial class UpdateRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdvProgramPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Advarics.ControlService.TestClient.AdvaricsControlService.CustomerInfo CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long PackageNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdateServerPathField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdvProgramPath {
            get {
                return this.AdvProgramPathField;
            }
            set {
                if ((object.ReferenceEquals(this.AdvProgramPathField, value) != true)) {
                    this.AdvProgramPathField = value;
                    this.RaisePropertyChanged("AdvProgramPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Advarics.ControlService.TestClient.AdvaricsControlService.CustomerInfo Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdToken {
            get {
                return this.IdTokenField;
            }
            set {
                if ((this.IdTokenField.Equals(value) != true)) {
                    this.IdTokenField = value;
                    this.RaisePropertyChanged("IdToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long PackageNo {
            get {
                return this.PackageNoField;
            }
            set {
                if ((this.PackageNoField.Equals(value) != true)) {
                    this.PackageNoField = value;
                    this.RaisePropertyChanged("PackageNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdateServerPath {
            get {
                return this.UpdateServerPathField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateServerPathField, value) != true)) {
                    this.UpdateServerPathField = value;
                    this.RaisePropertyChanged("UpdateServerPath");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateInfoResponse", Namespace="http://schemas.datacontract.org/2004/07/Advarics.ControlService.DataContracts.Fil" +
        "eTransfer")]
    [System.SerializableAttribute()]
    public partial class UpdateInfoResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Advarics.ControlService.TestClient.AdvaricsControlService.LogResponse[] LogsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Advarics.ControlService.TestClient.AdvaricsControlService.LogResponse[] Logs {
            get {
                return this.LogsField;
            }
            set {
                if ((object.ReferenceEquals(this.LogsField, value) != true)) {
                    this.LogsField = value;
                    this.RaisePropertyChanged("Logs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdvaricsControlService.IAdvaricsControlService")]
    public interface IAdvaricsControlService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdvaricsControlService/UploadFile", ReplyAction="http://tempuri.org/IAdvaricsControlService/UploadFileResponse")]
        Advarics.ControlService.TestClient.AdvaricsControlService.UploadInfoResponse UploadFile(Advarics.ControlService.TestClient.AdvaricsControlService.UploadFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdvaricsControlService/UploadFile", ReplyAction="http://tempuri.org/IAdvaricsControlService/UploadFileResponse")]
        System.Threading.Tasks.Task<Advarics.ControlService.TestClient.AdvaricsControlService.UploadInfoResponse> UploadFileAsync(Advarics.ControlService.TestClient.AdvaricsControlService.UploadFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdvaricsControlService/GetVersions", ReplyAction="http://tempuri.org/IAdvaricsControlService/GetVersionsResponse")]
        Advarics.ControlService.TestClient.AdvaricsControlService.VersionInfoResponse GetVersions(Advarics.ControlService.TestClient.AdvaricsControlService.VersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdvaricsControlService/GetVersions", ReplyAction="http://tempuri.org/IAdvaricsControlService/GetVersionsResponse")]
        System.Threading.Tasks.Task<Advarics.ControlService.TestClient.AdvaricsControlService.VersionInfoResponse> GetVersionsAsync(Advarics.ControlService.TestClient.AdvaricsControlService.VersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdvaricsControlService/UpdateCustomer", ReplyAction="http://tempuri.org/IAdvaricsControlService/UpdateCustomerResponse")]
        Advarics.ControlService.TestClient.AdvaricsControlService.UpdateInfoResponse UpdateCustomer(Advarics.ControlService.TestClient.AdvaricsControlService.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdvaricsControlService/UpdateCustomer", ReplyAction="http://tempuri.org/IAdvaricsControlService/UpdateCustomerResponse")]
        System.Threading.Tasks.Task<Advarics.ControlService.TestClient.AdvaricsControlService.UpdateInfoResponse> UpdateCustomerAsync(Advarics.ControlService.TestClient.AdvaricsControlService.UpdateRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdvaricsControlServiceChannel : Advarics.ControlService.TestClient.AdvaricsControlService.IAdvaricsControlService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdvaricsControlServiceClient : System.ServiceModel.ClientBase<Advarics.ControlService.TestClient.AdvaricsControlService.IAdvaricsControlService>, Advarics.ControlService.TestClient.AdvaricsControlService.IAdvaricsControlService {
        
        public AdvaricsControlServiceClient() {
        }
        
        public AdvaricsControlServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdvaricsControlServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdvaricsControlServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdvaricsControlServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Advarics.ControlService.TestClient.AdvaricsControlService.UploadInfoResponse UploadFile(Advarics.ControlService.TestClient.AdvaricsControlService.UploadFileRequest request) {
            return base.Channel.UploadFile(request);
        }
        
        public System.Threading.Tasks.Task<Advarics.ControlService.TestClient.AdvaricsControlService.UploadInfoResponse> UploadFileAsync(Advarics.ControlService.TestClient.AdvaricsControlService.UploadFileRequest request) {
            return base.Channel.UploadFileAsync(request);
        }
        
        public Advarics.ControlService.TestClient.AdvaricsControlService.VersionInfoResponse GetVersions(Advarics.ControlService.TestClient.AdvaricsControlService.VersionRequest request) {
            return base.Channel.GetVersions(request);
        }
        
        public System.Threading.Tasks.Task<Advarics.ControlService.TestClient.AdvaricsControlService.VersionInfoResponse> GetVersionsAsync(Advarics.ControlService.TestClient.AdvaricsControlService.VersionRequest request) {
            return base.Channel.GetVersionsAsync(request);
        }
        
        public Advarics.ControlService.TestClient.AdvaricsControlService.UpdateInfoResponse UpdateCustomer(Advarics.ControlService.TestClient.AdvaricsControlService.UpdateRequest request) {
            return base.Channel.UpdateCustomer(request);
        }
        
        public System.Threading.Tasks.Task<Advarics.ControlService.TestClient.AdvaricsControlService.UpdateInfoResponse> UpdateCustomerAsync(Advarics.ControlService.TestClient.AdvaricsControlService.UpdateRequest request) {
            return base.Channel.UpdateCustomerAsync(request);
        }
    }
}
